package Domain;
// Generated 14/04/2019 11:16:50 PM by Hibernate Tools 4.3.1



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer idusers;
     private String userName;
     private String surname;
     private String email;
     private long telephone;
     private String city;
     private String pc;

    public Users() {
    }

    public Users(String userName, String surname, String email, long telephone, String city, String pc) {
       this.userName = userName;
       this.surname = surname;
       this.email = email;
       this.telephone = telephone;
       this.city = city;
       this.pc = pc;
    }
   
    public Integer getIdusers() {
        return this.idusers;
    }
    
    public void setIdusers(Integer idusers) {
        this.idusers = idusers;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public long getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(long telephone) {
        this.telephone = telephone;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getPc() {
        return this.pc;
    }
    
    public void setPc(String pc) {
        this.pc = pc;
    }




}


